spring:
  profiles: 
    active:
    - dev

---
server:
  port: 8201
spring:
  profiles: dev  #开发环境
  appliction: 
    name: smart-config-client 
eureka: 
  client: 
    server-url: 
      defaultZone:  http://eureka-dev.com:7001/eureka/
    

---
server:
  port: 8202
spring:
  profiles: test  #开发环境
  appliction: 
    name: smart-config-client 
eureka: 
  client: 
    server-url: 
      defaultZone:  http://eureka-test.com:7001/eureka/